language: python

python:
  - "2.7"
  - "3.6"

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.0-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.6.0-amd64.deb && sudo service elasticsearch start

install:
  - pip install tox-travis
  - pip install codecov

before_script:
  - sleep 10

script: tox

after_success:
  - codecov

notifications:
  email: false
