language: python

python:
  - "2.7"
  - "3.6"

services:
  - elasticsearch

install:
  - pip install tox-travis
  - pip install codecov

before_script:
  - sleep 10

script: tox

after_success:
  - codecov

notifications:
  email: false
