language: python

python:
  - "2.7"
  - "3.6"

addons:
  apt:
    packages:
      - default-jre

install:
  - pip install tox-travis
  - pip install codecov
  - mkdir /tmp/elasticsearch
  - wget -O - https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.0-linux-x86_64.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch -d -E path.repo=/tmp -E repositories.url.allowed_urls='http://*' -E node.attr.testattr=test

script: tox

after_success:
  - codecov

notifications:
  email: false
